name: Sanity & formatting checks

on:
  push:
  pull_request:

jobs:
  astro-check:
    name: Check with Astro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            .astro
            node_modules
          key: ${{ runner.os }}-astro-check-${{ github.repository_id }}-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-astro-check-${{ github.repository_id }}-
            ${{ runner.os }}-astro-check-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: npm ci
        run: pnpm install --frozen-lockfile

      - name: Check with Astro
        id: check-astro
        run: pnpm exec astro check

  prettier-check:
    name: Check with Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache .astro and node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-prettier-lint-${{ github.repository_id }}-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-prettier-lint-${{ github.repository_id }}-
            ${{ runner.os }}-prettier-lint-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: npm ci
        run: pnpm install --frozen-lockfile

      - name: Check with Prettier
        id: check-formatting
        run: pnpm exec prettier --check .
