name: Prettier check

on:
  push:
  pull_request_target:

permissions:
  contents: write

jobs:
  prettier-check:
    name: Check with Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check with Prettier
        id: check-formatting
        run: pnpm exec prettier --check .
